### PR TITLE
fixed (probably) the flickering LEDs

### LINKED ISSUE #220: LEDs are flickering in disable

### PR DESCRIPTION
**Pull request by Hyrumthehotscott**
Closes #220

### CODE REVIEW

File: src/main/java/frc/robot/subsystems/LEDs.java [hunk 1]
```diff
@@ -73,6 +71,14 @@ public void clearAnimation() {
     CANdle.setLEDs(0, 0, 0, 0, 0, 0);
   }
 
+  /**
+   * Clears a specified chunk of LEDs of the current animation or color
+   */
+  public void clearAnimationChunk(int startIdx, int count) {
+    setLEDBrightness(0);
```
Comment (AlenaNguyen) [inline src/main/java/frc/robot/subsystems/LEDs.java]: You don't need to setLEDBrightness to 0. You already cleared the LED color when you set the RGB values to 0. If you set the LED Brightness to zero, this'll turn off the LEDs completely 🥺

File: src/main/java/frc/robot/RobotContainer.java [hunk 2]
```diff
@@ -404,6 +403,7 @@ public void setAutoPlacementLEDs(Optional<Alliance> alliance) {
 
       subLEDs.setIndividualLED(YTranslationColor, 5);
       subLEDs.setIndividualLED(YTranslationColor, 6);
+      subLEDs.clearAnimationChunk(8, 0);
```
Comment (AlenaNguyen) [inline src/main/java/frc/robot/RobotContainer.java]: Before testing, set the count parameter to be greater than 0 (maybe 50-100 so you could actually see it do something). Otherwise, you're saying "apply this color to 0 LEDs!" and it won't do anything :(
While testing, try to find the actual number of LEDs that it will take to clear a whole strip.

**Review by AlenaNguyen — DISMISSED** [review]

File: src/main/java/frc/robot/RobotContainer.java (hunk 2 above)
Comment (alicekuznetsov) [reply src/main/java/frc/robot/RobotContainer.java]: On another note, do we want to be sending requests to the LEDs every loop? It would save processing power if we only sent requests to the LEDs (especially clearing the animation) if there is a change in their desired color. In this case, we would only clear the animation if the current status of the LEDs is not clear

Comment (AlenaNguyen) [reply src/main/java/frc/robot/RobotContainer.java]: hehe "note." But yes that would be better. I just don't have a clear (hehe) plan on how to do that at the moment.

Comment (alicekuznetsov) [reply src/main/java/frc/robot/RobotContainer.java]: maybe have a variable in the subLEDs class that stores the last desired animation? It would get a little weird since you set the LEDs to both animations and colors (int[]) but that would probably be the start of it.
You'd effectively need to turn the LEDs into a state machine

**Review by TaylerUva — APPROVED** [review]

**Review by TaylerUva — APPROVED** [review]

File: src/main/java/frc/robot/RobotContainer.java (hunk 2 above)
Comment (TaylerUva) [reply src/main/java/frc/robot/RobotContainer.java]: References in new issue
